# Generated by Django 2.1.1 on 2018-10-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20181006_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, upload_to='uploads/post/cover/%Y/%m/%d/'),
        ),
    ]
