# Generated by Django 2.1.1 on 2018-10-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20181005_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
