# Generated by Django 2.1 on 2018-09-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20180912_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basecomment',
            old_name='user_name',
            new_name='username',
        ),
    ]
