# Generated by Django 2.1.1 on 2018-10-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_reply_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecomment',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
