# Generated by Django 2.1 on 2018-09-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
    ]
