# Generated by Django 2.0.5 on 2018-07-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reputation',
            field=models.IntegerField(default=1),
        ),
    ]
