# Generated by Django 2.1.1 on 2018-10-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181005_0103'),
    ]

    operations = [
    ]
