# Generated by Django 2.1.1 on 2018-10-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181006_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='followers',
            new_name='pub_followers',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(to='user.Publication'),
        ),
    ]
