# Generated by Django 2.1.1 on 2018-10-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_publication_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='user.Publication'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_followers',
            field=models.ManyToManyField(blank=True, to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='categories',
            field=models.ManyToManyField(blank=True, to='user.Category'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='roles',
            field=models.ManyToManyField(blank=True, to='user.Role'),
        ),
    ]
